<?php

namespace ContainerD6FyEWp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Obm7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.obm__7_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.obm__7_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
        ], [
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
        ]);
    }
}
