<?php

namespace ContainerD6FyEWp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOwnerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9LAmx1C.App\Entity\Owner' shared service.
     *
     * @return \App\Entity\Owner
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.9LAmx1C": it references class "App\\Entity\\Owner" but no such service exists.');
    }
}
