<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8n4PxqM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8n4PxqM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8n4PxqM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8n4PxqM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8n4PxqM\App_KernelDevDebugContainer([
    'container.build_hash' => '8n4PxqM',
    'container.build_id' => '17636f11',
    'container.build_time' => 1637067715,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8n4PxqM');
