<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM1LkJVc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM1LkJVc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM1LkJVc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM1LkJVc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerM1LkJVc\App_KernelDevDebugContainer([
    'container.build_hash' => 'M1LkJVc',
    'container.build_id' => 'ba3b1587',
    'container.build_time' => 1637060885,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM1LkJVc');
