<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOyA8z7Q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOyA8z7Q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOyA8z7Q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOyA8z7Q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOyA8z7Q\App_KernelDevDebugContainer([
    'container.build_hash' => 'OyA8z7Q',
    'container.build_id' => 'db240631',
    'container.build_time' => 1637149551,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOyA8z7Q');
