<?php

namespace Container8n4PxqM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BDCyWLf.App\Entity\Transaction' shared service.
     *
     * @return \App\Entity\Transaction
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.BDCyWLf": it references class "App\\Entity\\Transaction" but no such service exists.');
    }
}
