<?php

namespace ContainerOyA8z7Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H4z8DQIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h4z8DQI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h4z8DQI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'account' => ['privates', '.errored..service_locator.h4z8DQI.App\\Entity\\Account', NULL, 'Cannot autowire service ".service_locator.h4z8DQI": it references class "App\\Entity\\Account" but no such service exists.'],
        ], [
            'account' => 'App\\Entity\\Account',
        ]);
    }
}
