<?php

namespace ContainerOyA8z7Q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BDCyWLfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BDCyWLf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BDCyWLf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'transaction' => ['privates', '.errored..service_locator.BDCyWLf.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.BDCyWLf": it references class "App\\Entity\\Transaction" but no such service exists.'],
        ], [
            'transaction' => 'App\\Entity\\Transaction',
        ]);
    }
}
