<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Account extends \App\Entity\Account implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'iban', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'balance', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'owner', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'debitTransactions', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'creditTransactions', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'minimumBalance', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'senders'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'iban', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'balance', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'owner', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'debitTransactions', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'creditTransactions', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'minimumBalance', '' . "\0" . 'App\\Entity\\Account' . "\0" . 'senders'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Account $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getIban(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIban', []);

        return parent::getIban();
    }

    /**
     * {@inheritDoc}
     */
    public function setIban(string $iban): \App\Entity\Account
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIban', [$iban]);

        return parent::setIban($iban);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalance(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalance', []);

        return parent::getBalance();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalance(int $balance): \App\Entity\Account
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalance', [$balance]);

        return parent::setBalance($balance);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(string $type): \App\Entity\Account
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner(): ?\App\Entity\Owner
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(?\App\Entity\Owner $owner): \App\Entity\Account
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$owner]);

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getDebitTransactions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDebitTransactions', []);

        return parent::getDebitTransactions();
    }

    /**
     * {@inheritDoc}
     */
    public function addDebitTransaction(\App\Entity\Transaction $debitTransaction): \App\Entity\Account
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDebitTransaction', [$debitTransaction]);

        return parent::addDebitTransaction($debitTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDebitTransaction(\App\Entity\Transaction $debitTransaction): \App\Entity\Account
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDebitTransaction', [$debitTransaction]);

        return parent::removeDebitTransaction($debitTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreditTransactions(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreditTransactions', []);

        return parent::getCreditTransactions();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreditTransaction(\App\Entity\Transaction $creditTransaction): \App\Entity\Account
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreditTransaction', [$creditTransaction]);

        return parent::addCreditTransaction($creditTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreditTransaction(\App\Entity\Transaction $creditTransaction): \App\Entity\Account
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreditTransaction', [$creditTransaction]);

        return parent::removeCreditTransaction($creditTransaction);
    }

    /**
     * {@inheritDoc}
     */
    public function getMinimumBalance(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMinimumBalance', []);

        return parent::getMinimumBalance();
    }

    /**
     * {@inheritDoc}
     */
    public function setMinimumBalance(int $minimumBalance): \App\Entity\Account
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMinimumBalance', [$minimumBalance]);

        return parent::setMinimumBalance($minimumBalance);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenders(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenders', []);

        return parent::getSenders();
    }

    /**
     * {@inheritDoc}
     */
    public function addSender(\App\Entity\Owner $sender): \App\Entity\Account
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSender', [$sender]);

        return parent::addSender($sender);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSender(\App\Entity\Owner $sender): \App\Entity\Account
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSender', [$sender]);

        return parent::removeSender($sender);
    }

}
