<?php

namespace ContainerY6F1Xwv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Sj9cQXUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Sj9cQXU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Sj9cQXU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AccountController::delete' => ['privates', '.service_locator.h4z8DQI', 'get_ServiceLocator_H4z8DQIService', true],
            'App\\Controller\\AccountController::edit' => ['privates', '.service_locator.h4z8DQI', 'get_ServiceLocator_H4z8DQIService', true],
            'App\\Controller\\AccountController::index' => ['privates', '.service_locator.SYsIV8x', 'get_ServiceLocator_SYsIV8xService', true],
            'App\\Controller\\AccountController::show' => ['privates', '.service_locator.h4z8DQI', 'get_ServiceLocator_H4z8DQIService', true],
            'App\\Controller\\OwnerController::delete' => ['privates', '.service_locator.9LAmx1C', 'get_ServiceLocator_9LAmx1CService', true],
            'App\\Controller\\OwnerController::edit' => ['privates', '.service_locator.9LAmx1C', 'get_ServiceLocator_9LAmx1CService', true],
            'App\\Controller\\OwnerController::index' => ['privates', '.service_locator.zpQjwkF', 'get_ServiceLocator_ZpQjwkFService', true],
            'App\\Controller\\OwnerController::show' => ['privates', '.service_locator.9LAmx1C', 'get_ServiceLocator_9LAmx1CService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\AccountController:delete' => ['privates', '.service_locator.h4z8DQI', 'get_ServiceLocator_H4z8DQIService', true],
            'App\\Controller\\AccountController:edit' => ['privates', '.service_locator.h4z8DQI', 'get_ServiceLocator_H4z8DQIService', true],
            'App\\Controller\\AccountController:index' => ['privates', '.service_locator.SYsIV8x', 'get_ServiceLocator_SYsIV8xService', true],
            'App\\Controller\\AccountController:show' => ['privates', '.service_locator.h4z8DQI', 'get_ServiceLocator_H4z8DQIService', true],
            'App\\Controller\\OwnerController:delete' => ['privates', '.service_locator.9LAmx1C', 'get_ServiceLocator_9LAmx1CService', true],
            'App\\Controller\\OwnerController:edit' => ['privates', '.service_locator.9LAmx1C', 'get_ServiceLocator_9LAmx1CService', true],
            'App\\Controller\\OwnerController:index' => ['privates', '.service_locator.zpQjwkF', 'get_ServiceLocator_ZpQjwkFService', true],
            'App\\Controller\\OwnerController:show' => ['privates', '.service_locator.9LAmx1C', 'get_ServiceLocator_9LAmx1CService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\AccountController::delete' => '?',
            'App\\Controller\\AccountController::edit' => '?',
            'App\\Controller\\AccountController::index' => '?',
            'App\\Controller\\AccountController::show' => '?',
            'App\\Controller\\OwnerController::delete' => '?',
            'App\\Controller\\OwnerController::edit' => '?',
            'App\\Controller\\OwnerController::index' => '?',
            'App\\Controller\\OwnerController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AccountController:delete' => '?',
            'App\\Controller\\AccountController:edit' => '?',
            'App\\Controller\\AccountController:index' => '?',
            'App\\Controller\\AccountController:show' => '?',
            'App\\Controller\\OwnerController:delete' => '?',
            'App\\Controller\\OwnerController:edit' => '?',
            'App\\Controller\\OwnerController:index' => '?',
            'App\\Controller\\OwnerController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
