<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCTJwPRx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCTJwPRx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCTJwPRx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCTJwPRx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCTJwPRx\App_KernelDevDebugContainer([
    'container.build_hash' => 'CTJwPRx',
    'container.build_id' => '4f46bf46',
    'container.build_time' => 1636973946,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCTJwPRx');
